import Head from "next/head";

import Header from "../components/header";
import About from "../sections/about";
import OurServices from "../sections/services";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <OurServices />
      <About />
      <main></main>
    </div>
  );
}
